### PR TITLE
Fix build against GCC 16

### PR DESCRIPTION
**Pull request by DimStar77**
- https://bugzilla.opensuse.org/show_bug.cgi?id=1243674#c5 (tracker)
- https://bugzilla.suse.com/show_bug.cgi?id=1256972 (libyui specific)

Build of libyui fails against GCC 16 - so far I've identified two modules failing:
* libyui-ncurses
* libyui-qt

ncurses fails with:
```
[   18s] /home/abuild/rpmbuild/BUILD/libyui-ncurses-4.7.6-build/libyui-4.7.6/libyui-ncurses/src/NCtext.cc:348:34: error: use of deleted function ‘std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, wchar_t) [with _Traits = char_traits<char>]’
[   18s]   348 |         str << ':' << obj.hotkey() << " at " << obj.hotpos();
[   18s]       |                                  ^
```

Qt fails with:
```
[   66s] /home/abuild/rpmbuild/BUILD/libyui-qt-4.7.6-build/libyui-4.7.6/libyui-qt/src/YQWizard.cc:962:52: error: arithmetic between different enumeration types ‘Qt::KeyboardModifier’ and ‘Qt::Key’ is deprecated [-Werror=deprecated-enum-enum-conversion]
```

### CODE REVIEW

**Comment by DimStar77** [comment]
For reference, libyui with this PR (added as patch) is built in
https://build.opensuse.org/package/show/home:dimstar:Factory/libyui

* Staging_Gcc7 -> builds using GCC 16 (repo name is historic)
* All the other repos build using GCC 15.3

File: package/libyui.changes [hunk 1]
```diff
@@ -1,3 +1,14 @@
+-------------------------------------------------------------------
+Thu Jul 16 08:45:59 UTC 2026 - Dominique Leuenberger <dimstar@opensuse.org>
+
+- Fix build against GCC 16 (boo#1243674#c5):
```
Comment (mvidner) [inline package/libyui.changes]:
```suggestion
- Fix build against GCC 16 (boo#1243674#c5, boo#1256972):
```

Add specific bug reference for this package, https://bugzilla.suse.com/show_bug.cgi?id=1256972

File: package/libyui.changes [hunk 2]
```diff
@@ -1,3 +1,14 @@
...
+  + ncruses: Fix wchar_t stream insertion
```
Comment (mvidner) [inline package/libyui.changes]:
```suggestion
  + ncurses: Fix wchar_t stream insertion
```

tpyo

**Review by mvidner — APPROVED** [review]
Thank you DimStar, nice fixes! LGTM
